---
# Central configuration for repository URLs
# This file contains the canonical repository information used throughout the project
# Update this file when the repository location changes

repository:
  git_url: "https://github.com/capnajax/integration-jam-in-a-box.git"
  raw_base_url: "https://raw.githubusercontent.com/capnajax/integration-jam-in-a-box"
  
# Template variables that can be used in other YAML files
# Usage: {{REPO_GIT_URL}} and {{REPO_RAW_BASE_URL}}
template_vars:
  REPO_GIT_URL: "https://github.com/capnajax/integration-jam-in-a-box.git"
  REPO_RAW_BASE_URL: "https://raw.githubusercontent.com/capnajax/integration-jam-in-a-box"